Repository Isabellagarf/Research_Compendium_test, pull requests merged in 2025-03, with the labels that each got.

#25 made a change on line 11
  _code/daily_presence_cetaceans.R
Labels: help wanted

#32 made a change on line 107
  _code/daily_presence_cetaceans.R
Labels: help wanted

#26 Making a change on line 41
  _code/daily_presence_cetaceans.R
Labels: enhancement

#30 change on line 32
  _code/daily_presence_cetaceans.R
Labels: good first issue

#33 Julianne's change to line 11
  _code/daily_presence_cetaceans.R
Labels: enhancement

#31 Update daily_presence_cetaceans.R
  _code/daily_presence_cetaceans.R
Labels: invalid

#27 Update daily_presence_cetaceans.R
  _code/daily_presence_cetaceans.R
Labels: wontfix
